---
# Configuration tasks

- block:

  - name: setup a fact with all necessary subnet include config files
    set_fact:
      dhcpd_subnet_include_files: >-
        {{ dhcpd_subnets
          | map(attribute='subnet')
          | map('regex_replace', '^', dhcpd_subnets_include_dir + "/")
          | map('regex_replace', '$', '.conf')
          | list }}

  - name: setup a fact with all necessary static include config files
    set_fact:
      dhcpd_static_include_files: >-
        {{ dhcpd_static
          | map(attribute='name')
          | map('regex_replace', '^', dhcpd_static_include_dir + "/")
          | map('regex_replace', '$', '.conf')
          | list }}

  - name: setup a fact with all necessary include files
    set_fact:
      dhcpd_include_files: >-
        {{ dhcpd_static_include_files
          + dhcpd_subnet_include_files }}

  - name: search include files that already exists
    find:
      paths: "{{ item }}"
      patterns: "*.conf"
    with_items:
      - "{{ dhcpd_subnets_include_dir }}"
      - "{{ dhcpd_static_include_dir }}"
    register: search_includes_result

  - name: delete unnecessary include files
    file:
      path: "{{ item.path }}"
      state: absent
    when:
      - item.path | basename not in dhcpd_include_files
    with_items: >-
      {{ search_includes_result.results
        | sum(attribute="files", start=[] )
        | default([]) }}

  - name: create configuration files for subnets
    template:
      src: subnet.template.j2
      dest: "{{ dhcpd_subnets_include_dir }}/{{ item.subnet }}.conf"
      owner: root
      group: root
      mode: 0644
      backup: no
    with_items: "{{ dhcpd_subnets }}"
    register: configure_dhcpd_subnets_result
    notify:
      - dhcpd restart

  - name: create configuration files for static addresses
    template:
      src: static.template.j2
      dest: "{{ dhcpd_static_include_dir }}/{{ item.hostname }}.conf"
      owner: root
      group: root
      mode: 0644
      backup: no
    with_items: "{{ dhcpd_all_static_addresses | default([]) }}"
    register: configure_static_addresses_result
    notify:
      - dhcpd restart

  - name: create dhcpd main configuration file
    template:
      src: dhcpd.template.j2
      dest: /etc/dhcp/dhcpd.conf
      owner: root
      group: root
      mode: 0644
      backup: no
    register: create_main_config_result
    notify:
      - dhcpd restart

  tags:
    - role::dhcpd
    - role::dhcpd::configure
