---
# Configuration tasks block

- block:

  - name: search static dhcp addreses config files defined in other hosts
    set_fact:
      files: >
        {{ hostvars[item]['dhcpd_static_addresses']
          | map(attribute='hostname')
          | map('regex_replace', '$', '.conf') | list }}
    when: "'dhcpd_static_addresses' in hostvars[item]"
    with_items: "{{ groups['all'] }}"
    register: search_external_files_result

  - name: setup a fact with all necessary external config files from other hosts
    set_fact:
      dhcpd_external_include_files: >
        {{ search_external_files_result.results
          | reject('skipped', 'defined')
          | map(attribute='ansible_facts')
          | map(attribute='files')
          | sum(none, [])
          | list }}

  - name: setup a fact with all necessary own include config files
    set_fact:
      dhcpd_own_include_files: >
       {{ dhcpd_subnets
          | map(attribute='subnet')
          | map('regex_replace', '$', '.conf')
          | list
          + dhcpd_static_addresses
          | map(attribute='hostname')
          | map('regex_replace', '$', '.conf')
          | list }}

  - name: setup a fact with all necessary include files
    set_fact:
      dhcpd_include_files: >
        {{ dhcpd_external_include_files
          + dhcpd_own_include_files }}

  - name: search include files that exists
    find: paths="{{ dhcpd_include_files_dir }}" patterns="*.conf"
    register: search_includes_result
    delegate_to: "{{ dhcpd_remote_server }}"

  - name: delete not necessary include files
    file: path={{ item.path }} state=absent
    when: "'{{ item.path | basename }}' not in dhcpd_include_files"
    with_items: "{{ search_includes_result.files }}"

  - name: configure dhcpd subnets
    template:
      src: subnet.template.j2
      dest: "{{ dhcpd_include_files_dir }}/{{ item.subnet }}.conf"
      owner: root
      group: root
      mode: 0644
      backup: yes
    with_items: "{{ dhcpd_subnets }}"
    register: configure_dhcpd_subnets_result
    when: "not dhcpd_client_only"

  - name: create main configuration file
    template:
      src: dhcpd.template.j2
      dest: /etc/dhcp/dhcpd.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: create_main_config_result
    delegate_to: "{{ dhcpd_remote_server }}"

  - name: restart dhcpd service
    service: name=dhcpd state=restarted enabled=yes
    delegate_to: "{{ dhcpd_remote_server }}"
    when: >
      configure_dhcpd_subnets_result.changed
      or create_main_config_result.changed

  tags: configure
