---
# Delete unmanaged include files

- block:

  - name: disable unamanged files deletion if the role is called from a clients
    set_fact:
      dhcpd_delete_unmanaged: false
    when: inventory_hostname != dhcpd_server

  - name: setup a fact with all necessary subnet include config files
    set_fact:
      dhcpd_subnet_include_files: >-
        {{ dhcpd_subnet_addresses
          | selectattr('state', 'equalto', 'present')
          | map(attribute='subnet')
          | map('regex_replace', '^', dhcpd_subnets_include_dir + "/")
          | map('regex_replace', '$', '.conf')
          | list }}

  - name: setup a fact with all necessary static include config files
    set_fact:
      dhcpd_static_include_files: >-
        {{ dhcpd_static_addresses
          | selectattr('state', 'equalto', 'present')
          | map(attribute='hostname')
          | map('regex_replace', '^', dhcpd_static_include_dir + "/")
          | map('regex_replace', '$', '.conf')
          | list }}

  - name: setup a fact with all necessary include files
    set_fact:
      dhcpd_include_files: >-
        {{ dhcpd_static_include_files
          + dhcpd_subnet_include_files }}

  - name: delete unamanged include files
    file:
      path: "{{ item.path }}"
      state: absent
    when: item.path | default('') not in dhcpd_include_files
    with_items: >-
      {{ search_includes_result.results
        | sum(attribute="files", start=[] )
        | default([]) }}
    register: dhcpd_delete_unmanaged_result
    loop_control:
      label: "{{ item.path }}"

  when: dhcpd_delete_unmanaged
  delegate_to: "{{ dhcpd_server }}"
  tags:
    - role::dhcpd
    - role::dhcpd::configure
