---
# Install tasks

- block:

  - name: install dhcpd packages
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ dhcpd_packages | default([]) }}"
    tags:
      - role::dhcpd
      - role::dhcpd::packages
      - role::dhcpd::install
