---
# Install tasks

- block:

  - name: install dhcpd packages
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ dhcpd_packages | default([]) }}"
    tags:
      - role::dhcpd
      - role::dhcpd::packages
      - role::dhcpd::install

  - name: create dhcpd required directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - "{{ dhcpd_subnets_include_dir }}"
      - "{{ dhcpd_static_include_dir }}"
    tags:
      - role::dhcpd
      - role::dhcpd::install
