---
# Role tasks

- name: install dhcpd
  include: install.yml
  static: false
  tags:
    - role::dhcpd
    - role::dhcpd::install

- name: configure dhcpd
  include: configure.yml
  static: false
  tags:
    - role::dhcpd
    - role::dhcpd::configure

- name: setup dhcpd service
  include: service.yml
  static: false
  tags:
    - role::dhcpd
    - role::dhcpd::service
