---
# Role tasks

- name: Setup fact to optimize further runs
  set_fact:
    dhcpd_deps_resolved: yes
  tags:
    - role::dhcpd

- name: Install dhcpd
  include_tasks: install.yml
  tags:
    - role::dhcpd
    - role::dhcpd::install

- name: Configure dhcpd
  include_tasks: configure.yml
  tags:
    - role::dhcpd
    - role::dhcpd::configure

- name: Setup dhcpd service
  include_tasks: service.yml
  tags:
    - role::dhcpd
    - role::dhcpd::service

- name: Upgrade from old versions
  include_tasks: upgrade.yml
  tags:
    - role::dhcpd
    - role::dhcpd::upgrade
