---
# Task to search include files that exist in the server

- name: search include files that exists
  find: paths="{{ dhcpd_include_files_dir }}" patterns="*.conf"
  register: search_includes_result
  delegate_to: "{{ dhcpd_server }}"

- name: search temporary include files that exists not older than 1h
  find:
    paths: "{{ dhcpd_include_files_dir }}/tmp"
    patterns: "*.conf"
    age_stamp: ctime
    age: -1h
  register: search_temporary_includes_result
  delegate_to: "{{ dhcpd_server }}"

- name: search temporary include files that exists older than 1h
  find:
    paths: "{{ dhcpd_include_files_dir }}/tmp"
    patterns: "*.conf"
    age_stamp: ctime
    age: 1h
  register: search_old_temporary_includes_result
  delegate_to: "{{ dhcpd_server }}"
