---
# Task to search include files that exist in the server

- name: search include files that exists
  find: paths="{{ dhcpd_include_files_dir }}" patterns="*.conf"
  register: search_includes_result
  delegate_to: "{{ dhcpd_server }}"
