---
# Service tasks

- name: enable and start dhcpd service
  service:
    name: dhcpd
    state: started
    enabled: yes
  when: inventory_hostname == dhcpd_server
  tags:
    - role::dhcpd
    - role::dhcpd::service
