---
# This handler is intended to allow other roles remove temporary static
# adddresses in a remote dhcpd server without having the full dhcpd role
#
# To use this handler setup a fact called dhcpd_temporary_static_addresses with
# the same format of dhcpd_static_addresses role variable.

- name: remove temporary static addresses
  file:
    path: "{{ dhcpd_include_files_dir }}/tmp/{{ item.hostname }}.conf"
    state: absent
  with_items: "{{ dhcpd_temporary_static_addresses }}"
  delegate_to: "{{ dhcpd_server }}"

- include: configure.yml
