---
# Upgrade tasks

- name: Upgrade dhcpd
  block:
    - name: Delete old config directories created by older versions of the role
      ansible.builtin.file:
        path: "{{ dhcpd_old_dir }}"
        state: absent
        owner: root
        group: root
        mode: 0755
      loop:
        - "{{ dhcpd_include_base_dir }}/dhcpd.static.d"
      loop_control:
        loop_var: dhcpd_old_dir
  tags:
    - role::dhcpd
    - role::dhcpd::uograde
