---

- name: Converge
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - role: amtega.dhcpd
      vars:
        dhcpd_subnets:
          - name: subnet0
            subnet: "{{ ansible_facts.default_ipv4.network }}"
            netmask: "{{ ansible_facts.default_ipv4.netmask }}"
            state: present

          - name: subnet1
            subnet: 192.168.13.0
            netmask: 255.255.255.0
            state: present
            routers:
              - 192.168.13.1
            dns_servers:
              - 192.168.13.2
              - 192.168.13.3
            ranges:
              - start: 192.168.13.100
                end: 192.168.13.120
            default_lease_time: 21600
            max_lease_time: 43200
            next_server: 192.168.13.13
            filename: pxelinux.0

          - name: subnet2
            subnet: 192.168.14.0
            netmask: 255.255.255.0
            state: present
            routers:
              - 192.168.14.1
            dns_servers:
              - 192.168.14.2
              - 192.168.14.3
            ranges:
              - start: 192.168.14.100
                end: 192.168.14.120
            default_lease_time: 21600
            max_lease_time: 43200
            next_server: 192.168.14.13
            filename: pxelinux.0

          - name: subnet3
            subnet: 192.168.15.0
            netmask: 255.255.255.0
            state: absent
            routers:
              - 192.168.15.1
            dns_servers:
              - 192.168.15.2
              - 192.168.15.3
            ranges:
              - start: 192.168.15.100
                end: 192.168.15.120
            default_lease_time: 21600
            max_lease_time: 43200
            next_server: 192.168.15.13
            filename: pxelinux.0

        dhcpd_hosts:
          - hostname: hostacme1
            mac: c5:6f:75:cc:00:01
            ipv4_address: 192.168.15.121
            state: present
            subnet: subnet1

          - hostname: hostacme2
            mac: c5:6f:75:cc:00:02
            ipv4_address: 192.168.15.122
            state: present

          - hostname: hostacme3
            mac: c5:6f:75:cc:00:03
            ipv4_address: 192.168.15.123
            state: absent
  tasks:
    - name: Test dhcpd server restart handler
      ansible.builtin.copy:
        content: ""
        dest: /tmp/emptyfile
        force: no
        mode: 0755
      notify:
        - dhcpd restart
