---
# Role handlers

- name: Dhcpd restart service
  ansible.builtin.service:
    name: dhcpd
    state: restarted
    enabled: yes
  listen:
    - dhcpd restart
  tags:
    - role::dhcpd
    - role::dhcpd::service
