---
# Role handlers

- name: dhcpd add temporary static addresses
  include: static_add_temporary.yml

- name: dhcpd remove temporary static addresses
  include: static_remove_temporary.yml

- name: dhcpd restart
  include: restart.yml
