---
# Role handlers

- name: restart service
  service:
    name: dhcpd
    state: restarted
    enabled: yes
  delegate_to: "{{ dhcpd_server }}"
  listen:
    - dhcpd restart
  tags:
    - role::dhcpd
    - role::dhcpd::service
