#!/bin/bash

set -ue

lock=/var/run/dhcpd_rebuild.lock
lock_fd=200
lock_wait=180

dhcpd_basedir=/etc/dhcp/dhserver.d
dhcpd_includes=$dhcpd_basedir/includes.conf

exec {lock_fd}>$lock
flock -w $lock_wait $lock_fd || exit 1

echo "" > $dhcpd_includes
include_dirs=`find $dhcpd_basedir -mindepth 1 -maxdepth 1 -type d`
for d in $include_dirs; do
  files=`find $d -mindepth 1 -maxdepth 1 -type f -name "*.conf"`
  for f in $files; do
    echo "include \"$f\";" >> $dhcpd_includes
  done
done

systemctl restart dhcpd
return_value=$?

rm -f $lock

exit $return_value
